[package]
name = "elf2table"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge.aparicio@ferrous-systems.com>"]
edition = "2018"

[dependencies]
decoder = { path = "../decoder" }
anyhow = "1.0.32"

[dependencies.object]
version = "0.21.0"
default-features = false
features = ["read_core", "elf", "std"]
