[package]
authors = ["Jorge Aparicio <jorge.aparicio@ferrous-systems.com>"]
edition = "2018"
name = "binfmt"
version = "0.1.0"

[dependencies]
binfmt-macros = { path = "macros" }
common = { path = "common" }

[workspace]
members = [
  ".",
  "decoder",
  "elf2table",
  "macros",
  "parser",
]
exclude = ["firmware"]