[package]
authors = ["Jorge Aparicio <jorge.aparicio@ferrous-systems.com>"]
edition = "2018"
name = "defmt-semihosting"
version = "0.1.0"
publish = false

[dependencies]
defmt = { path = "../.." }
cortex-m = "0.6.3"
cortex-m-semihosting = "0.3.5"
