[package]
authors = ["Jorge Aparicio <jorge.aparicio@ferrous-systems.com>"]
edition = "2018"
name = "firmware"
version = "0.1.0"
publish = false

[dependencies]
defmt = { path = "../.." }
defmt-semihosting = { path = "../defmt-semihosting" }
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.3"
panic-halt = "0.2.0"

[features]
defmt-default = [] # log at INFO, or TRACE, level and up
defmt-trace = []   # log at TRACE level and up
defmt-debug = []   # log at DEBUG level and up
defmt-info = []    # log at INFO level and up
defmt-warn = []    # log at WARN level and up
defmt-error = []   # log at ERROR level
default = ["defmt-default"]

[[bin]]
name = "log"
test = false
