[package]
authors = ["Jorge Aparicio <jorge.aparicio@ferrous-systems.com>"]
edition = "2018"
name = "firmware"
version = "0.1.0"

[dependencies]
binfmt = { path = "../.." }
binfmt-semihosting = { path = "../binfmt-semihosting" }
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.3"
panic-halt = "0.2.0"

[features]
binfmt-default = [] # log at INFO, or TRACE, level and up
binfmt-trace = []   # log at TRACE level and up
binfmt-debug = []   # log at DEBUG level and up
binfmt-info = []    # log at INFO level and up
binfmt-warn = []    # log at WARN level and up
binfmt-error = []   # log at ERROR level
default = ["binfmt-default"]

[[bin]]
name = "log"
test = false
