[package]
authors = ["Jorge Aparicio <jorge.aparicio@ferrous-systems.com>"]
edition = "2018"
name = "decoder"
version = "0.1.0"

[dependencies]
binfmt-parser = { path = "../parser" }
common = { path = "../common" }
leb128 = "0.2.4"
byteorder = "1"
colored = "2.0.0"
ryu = "1"
